"""Initial migration

Revision ID: 25cd8674f39a
Revises: 
Create Date: 2025-09-17 18:44:30.796829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25cd8674f39a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('max_discount', sa.Float(), nullable=True),
    sa.Column('discount_per_member', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('gallery', sa.JSON(), nullable=True),
    sa.Column('itinerary', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destinations_id'), 'destinations', ['id'], unique=False)
    op.create_index(op.f('ix_destinations_name'), 'destinations', ['name'], unique=False)
    op.create_index(op.f('ix_destinations_slug'), 'destinations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('analytics_materialized',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_materialized_date'), 'analytics_materialized', ['date'], unique=False)
    op.create_index(op.f('ix_analytics_materialized_id'), 'analytics_materialized', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_materialized_metric_name'), 'analytics_materialized', ['metric_name'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('min_size', sa.Integer(), nullable=True),
    sa.Column('max_size', sa.Integer(), nullable=True),
    sa.Column('current_size', sa.Integer(), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('final_price_per_person', sa.Float(), nullable=False),
    sa.Column('price_calc', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_table('homepage_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('cta_text', sa.String(), nullable=True),
    sa.Column('cta_link', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homepage_messages_id'), 'homepage_messages', ['id'], unique=False)
    op.create_table('interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('user_phone', sa.String(), nullable=True),
    sa.Column('num_people', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('budget_min', sa.Float(), nullable=True),
    sa.Column('budget_max', sa.Float(), nullable=True),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('client_uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interests_client_uuid'), 'interests', ['client_uuid'], unique=True)
    op.create_index(op.f('ix_interests_id'), 'interests', ['id'], unique=False)
    op.create_index(op.f('ix_interests_user_email'), 'interests', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interests_user_email'), table_name='interests')
    op.drop_index(op.f('ix_interests_id'), table_name='interests')
    op.drop_index(op.f('ix_interests_client_uuid'), table_name='interests')
    op.drop_table('interests')
    op.drop_index(op.f('ix_homepage_messages_id'), table_name='homepage_messages')
    op.drop_table('homepage_messages')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_analytics_materialized_metric_name'), table_name='analytics_materialized')
    op.drop_index(op.f('ix_analytics_materialized_id'), table_name='analytics_materialized')
    op.drop_index(op.f('ix_analytics_materialized_date'), table_name='analytics_materialized')
    op.drop_table('analytics_materialized')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_destinations_slug'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_name'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_id'), table_name='destinations')
    op.drop_table('destinations')
    # ### end Alembic commands ###