"""Add travel specific fields to users table

Revision ID: 752c18db175d
Revises: da2c3a9f3b83
Create Date: 2025-09-18 10:16:19.342708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '752c18db175d'
down_revision = 'da2c3a9f3b83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passport_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('dietary_restrictions', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('medical_conditions', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('travel_preferences', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'travel_preferences')
    op.drop_column('users', 'medical_conditions')
    op.drop_column('users', 'dietary_restrictions')
    op.drop_column('users', 'passport_number')
    # ### end Alembic commands ###